spring:
  application:
    name: persona-api

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "${DATASOURCE_URL:jdbc:mysql://localhost:3307/credic_select?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8}"
    username: "${DATASOURCE_USERNAME:}"
    password: "${DATASOURCE_PASSWORD:}"

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
