spring:
  application:
    name: persona-api

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "${DATASOURCE_URL:jdbc:mysql://localhost:3307/credic_select?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8}"
    username: "${DATASOURCE_USERNAME:}"
    password: "${DATASOURCE_PASSWORD:}"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Logger config
logging:
  level:
    org:
      springframework: off
      hibernate:
        SQL: info
        type:
          descriptor:
            sql:
              BasicBinder: info


# Swagger config
springdoc:
  api-docs:
    path: /api/v1/select/docs
  swagger-ui:
    path: /api/v1/select/swagger-ui.html
    display-request-duration: true
    disable-swagger-default-url: true
